# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/charles/PycharmProjects/Hangman/hangman/designerforms/resultsdialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultDialog(object):
    def setupUi(self, ResultDialog):
        ResultDialog.setObjectName("GameResultDialog")
        ResultDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ResultDialog.resize(320, 200)
        ResultDialog.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResultDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_result = QtWidgets.QLabel(ResultDialog)
        self.label_result.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result.setText("")
        self.label_result.setScaledContents(True)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(ResultDialog)
        QtCore.QMetaObject.connectSlotsByName(ResultDialog)

    def retranslateUi(self, ResultDialog):
        _translate = QtCore.QCoreApplication.translate
        ResultDialog.setWindowTitle(_translate("GameResultDialog", "Dialog"))
